package lk.ijse.hibernate.coursework.navigation;

public enum Routes {

  ADMINLOGIN,BOOKMANAGE,USERMANAGE,BRANCHMANAGE,VIEWTRANSACTION,BORROWBOOKS,SEARCHBOOKS,USERLOGIN,USERSIGNUP,USERSETTING,HOMEADMIN,HOMEUSER
}
